apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  namespace: default
  description: Platform engineering team responsible for developer experience
spec:
  type: team
  profile:
    displayName: Platform Team
    email: platform-team@company.com
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: user-management-system
  namespace: default
  description: User management and authentication system
spec:
  owner: group:default/platform-team
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-microservice-api
  namespace: default
  description: REST API for my microservice
spec:
  type: openapi
  lifecycle: experimental
  owner: group:default/platform-team
  system: user-management-system
  definition:
    $text: ./openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-microservice
  namespace: default
  description: A demo microservice for user management
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: group:default/platform-team
  system: user-management-system
  providesApis:
    - my-microservice-api