site_name: My Microservice
site_description: Documentation for my microservice demo
site_author: Platform Team

docs_dir: docs
site_dir: site

nav:
  - Home: index.md

theme:
  name: material
  palette:
    primary: blue
    accent: blue

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true